name: Docker Compose Up for Production

on:
  push:
    branches: [ production ]

jobs:
  run:
    runs-on: self-hosted
    env:
      TZ: America/Sao_Paulo
      SITE_PATH: ${{ github.event.repository.name }}
      DOMAIN_NAME: ${{ secrets.GR_URL }}
      NEO4J_DATA: /opt/files/neo4jdata
      VOL_EMB: /opt/files/genai_emb
      NEO4J_USERNAME: ${{ secrets.GENAI_NEO4J_USERNAME }}
      NEO4J_PASSWORD: ${{ secrets.GENAI_NEO4J_PASSWORD }}
      LLM: ${{ secrets.GENAI_OLLAMA }}
      EMBEDDING_MODEL: "ollama"
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      LANGCHAIN_ENDPOINT: "https://api.smith.langchain.com"
      LANGCHAIN_TRACING_V2: true
      LANGCHAIN_PROJECT: ${{ secrets.LANGCHAIN_PROJECT }}
      LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
    steps:
      - uses: actions/checkout@v3

      #- n  ame: Login to Docker Hub (optional)
      #  run: |
      #    echo "$DOCKER_HUB_USERNAME:$DOCKER_HUB_PASSWORD" | docker login --username --password-stdin

      - name: Prepare
        if: always()
        run: mkdir -p $NEO4J_DATA && mkdir -p VOL_EMB/model && mkdir -p VOL_EMB/embed
        
      - name: Update Docker Compose
        if: always()
        run: docker compose build && docker compose pull

      - name: Stop Docker Compose
        if: always()
        run: docker compose down --remove-orphans 
        
      - name: Run Docker Compose Up
        run:  docker compose up -d --wait
